- name: Install apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - notion
    - dropbox
    - google-chrome
    - spotify
    - brave-browser
    - bruno
  tags:
    - "apps"
